name: âš¡Badges
on:
  push:
    branches:
      - main


jobs:
  badges-job:
    name: ğŸ“£ Generate cool badges
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/utils
    steps:

    # Necessary to push the generated badges to the repo
    - name: â¬‡ï¸ Checkout repo
      uses: actions/checkout@v4
    
    - run: npm install -g pnpm
    - run: pnpm install
    # ...

    # Necessary to generate the coverage report.
    # Make sure to add 'json-summary' to the coverageReporters in jest options
    - name: ğŸ” Tests
      run: pnpm coverage

    - name: âš™ï¸ Generating coverage badges
      uses: jpb06/coverage-badges-action@latest
      with:
        branches: main
        badges-icon: vitest
        coverage-path: ./coverage/coverage-summary.json
 